# Generated by Django 5.2.1 on 2025-05-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_profile_city_profile_country_profile_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postal_code',
        ),
    ]
