# Generated by Django 5.2 on 2025-05-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_remove_cart_status_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Cancel', 'Cancel')], default='Pending', max_length=10),
        ),
    ]
